// packages/ui/src/components/spinner.tsx
import type { CSSSize } from '@/lib/utils/styles';
import { cssVariable } from '@/lib/utils/styles';
import styles from './spinner/Spinner.module.scss';
export default function LoadingSpinner(props: LoadingSpinnerProps) {
  return (
    <div
      className={styles['loader']}
      aria-label="Loading..."
      role="status"
      style={cssVariable('--spinner-size', props.size ? `${props.size}px` : '40px')}
    />
  );
}

interface LoadingSpinnerProps {
  size?: CSSSize;
}

// packages/vue-ui/src/components/Spinner.vue
<template>
  <div
    :class="$style['loader']"
    aria-label="Loading..."
    role="status"
    :style="cssVariable('--spinner-size', size ?? '40px')"
  />
</template>

<script setup lang="ts">
import { cssVariable, type CSSSize } from '../lib/styles'

type Props = {
  size?: CSSSize
}

defineProps<Props>()
</script>

<style module src="./spinner/Spinner.module.scss"></style>
