// packages/vue-ui/src/widgets/SideCatalog.vue
<template>
  <CatalogTopLevelContainer>
    <Catalog ref="contentRef">
      <CatalogMobileHeader :selected-item-label="selectedItemLabel" :item-prefix="itemPrefix" />
      <CatalogSection ref="itemsList">
        <CatalogHeader :title="label">
          <CatalogSearchField placeholder="Search..." :model-value="queryText" @update:model-value="setQueryText" />
        </CatalogHeader>
        <CatalogItemsList
          :items="filteredItems"
          :on-select="onItemSelect"
          :is-selected="isSelected"
          :is-loading="isLoading"
        />
      </CatalogSection>
    </Catalog>
    <slot />
  </CatalogTopLevelContainer>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, useCssModule, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

import Catalog from '../components/catalog/Catalog.vue'
import CatalogHeader from '../components/catalog/CatalogHeader.vue'
import CatalogItemsList from '../components/catalog/CatalogItemsList.vue'
import CatalogMobileHeader from '../components/catalog/CatalogMobileHeader.vue'
import CatalogSearchField from '../components/catalog/CatalogSearchField.vue'
import CatalogSection from '../components/catalog/CatalogSection.vue'
import CatalogTopLevelContainer from '../components/catalog/CatalogTopLevelContainer.vue'
import { onBeforeMount } from 'vue'

const props = withDefaults(defineProps<SideCatalogProps>(), {
  isLoading: false,
  scrollMarginTop: 0,
  withRouteTransition: false,
  selectedItemLabel: '',
  itemPrefix: 'item: ',
  onSelect: undefined,
  isSelected: () => false,
  query: undefined,
})

const emit = defineEmits<{
  select: [item: SideCatalogItem, e: Event]
}>()

const route = useRoute()
const router = useRouter()

// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-arguments
const contentRef = ref<InstanceType<typeof CatalogTopLevelContainer>>()
// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-arguments
const itemsList = ref<InstanceType<typeof CatalogSection>>()
const queryText = ref<string>('')

const hasQuery = computed(() => queryText.value.length > 0)
const filteredItems = computed(() => {
  if (!hasQuery.value) return props.items
  if (!props.query) return props.items
  return props.query(queryText.value)
})

function onItemSelect(item: SideCatalogItem, e: Event): void {
  props.onSelect?.(item, e)
  emit('select', item, e)

  if (props.withRouteTransition && e instanceof MouseEvent) {
    e.preventDefault()
    const anchor = e.currentTarget as HTMLAnchorElement
    const href = anchor.getAttribute('href')
    if (href === null) return

    const newURL = new URL(href, window.location.href)
    newURL.searchParams.set('query', queryText.value)
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    newURL.searchParams.set('parentScrollY', String(contentRef.value?.$el?.scrollTop ?? 0))

    const baseURL = router.options.history.base
    const pathname = newURL.pathname.replace(baseURL, '/').replace('//', '/')
    router.push(pathname + newURL.search + newURL.hash)
  }
}

function setQueryText(value: string): void {
  queryText.value = value
  scrollToActive()
}

const style = useCssModule()
const haveCompletedMount = ref(false)

const onMountHasStarted = (): void => {
  if (haveCompletedMount.value) return
  if (props.isLoading) return
  if (!(contentRef.value || itemsList.value)) return

  const parentScrollY = route.query['parentScrollY']
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  if (parentScrollY !== undefined && parentScrollY !== '0' && contentRef.value?.$el) {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    contentRef.value.$el.scrollTop = Number(parentScrollY)
  }

  scrollToActive()

  const newQuery = { ...route.query }
  delete newQuery['parentScrollY']

  router.replace({ query: newQuery })
  haveCompletedMount.value = true
}

const scrollToActive = (): void => {
  const scrollMarginTopValue = props.scrollMarginTop
  setTimeout(() => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    if (!(contentRef.value?.$el && itemsList.value?.$el)) return
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
    const contentEl: HTMLElement = contentRef.value.$el
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
    const itemsEl: HTMLElement = itemsList.value.$el

    const targetLink = document.querySelector(`a.${style['active']}`)
    if (targetLink) {
      contentEl.scrollTo({
        behavior: 'smooth',
        top: (targetLink as HTMLElement).offsetTop - scrollMarginTopValue,
      })

      itemsEl.scrollTo({
        behavior: 'instant',
        top: (targetLink as HTMLElement).offsetTop - scrollMarginTopValue,
      })
    } else {
      contentEl.scrollTo({ top: 0 })
    }
  }, 0)
}

watch(
  () => [props.isLoading],
  () => {
    if (props.isLoading) return
    const searchQuery = route.query['query'] as string
    if (searchQuery) setQueryText(searchQuery)

    onMountHasStarted()
  }
)

onMounted(() => {
  onMountHasStarted()
})

onBeforeMount(() => {
  const searchQuery = route.query['query'] as string
  if (searchQuery) setQueryText(searchQuery)

  const newQuery = { ...route.query }
  delete newQuery['query']

  router.replace({ query: newQuery })
})

export type SideCatalogItem = {
  icon?: unknown // Vue component or string
  title: string
  url?: string
}

export type SideCatalogProps = {
  isLoading?: boolean
  isSelected?: (item: SideCatalogItem) => boolean
  itemPrefix?: string
  items: Array<SideCatalogItem>
  label: string
  onSelect?: (item: SideCatalogItem, e: Event) => void
  query?: (s: string) => Array<SideCatalogItem>
  scrollMarginTop?: number
  selectedItemLabel?: string
  withRouteTransition?: boolean
}
</script>

<style module src="../components/catalog/Catalog.module.scss" />

// packages/ui/src/widgets/SideCatalog.tsx
'use client';
import React, { useLayoutEffect, useMemo, useState } from 'react';

import Catalog from '@/components/catalog';
import useSearchParams from '@/hooks/useSearchParams';
import { useUrlState } from '../hooks/useURLState';

export default function SideCatalog(props: SideCatalogProps) {
  const contentRef = React.useRef<HTMLDivElement>(null);
  const itemsList = React.useRef<HTMLDivElement>(null);
  const { filteredItems, queryText, setQueryText, onSelect } = useSideCatalog(
    props,
    contentRef,
    itemsList
  );
  const { label, children } = props;

  return (
    <Catalog.TopLevelContainer>
      <Catalog.Container ref={contentRef}>
        <Catalog.MobileHeader
          selectedItemLabel={props.selectedItemLabel}
          itemPrefix={props.itemPrefix}
        />
        <Catalog.Section ref={itemsList}>
          <Catalog.Header title={label}>
            <Catalog.SearchField
              placeholder="Search..."
              value={queryText}
              onChange={(e) => setQueryText(e.target.value)}
            />
          </Catalog.Header>
          <Catalog.ItemsList
            items={filteredItems}
            onSelect={onSelect}
            isSelected={props.isSelected}
            isLoading={props.isLoading}
          />
        </Catalog.Section>
      </Catalog.Container>
      {children}
    </Catalog.TopLevelContainer>
  );
}

function useSideCatalog(
  {
    items,
    onSelect: userOnSelect,
    query,
    withRouteTransition,
    scrollMarginTop,
    isLoading,
  }: SideCatalogProps,
  contentRef: React.RefObject<HTMLDivElement | null>,
  itemsList: React.RefObject<HTMLDivElement | null>
) {
  const [queryText, setQueryText] = useState<string>('');
  const hasQuery = queryText.length > 0;
  const filteredItems = useMemo(() => {
    if (!hasQuery) return items;
    if (!query) return items;
    return query(queryText);
  }, [hasQuery, items, query, queryText]);

  const [urlState] = useUrlState();
  const [searchParams, setSearchParams] = useSearchParams();
  const { query: searchQueryFromUrl = '', parentScrollY = 0 } = urlState;

  useLayoutEffect(() => {
    if (isLoading) return;
    if (searchQueryFromUrl) {
      setQueryText(searchQueryFromUrl);
    }

    if (parentScrollY && contentRef.current) {
      contentRef.current.scrollTop = Number(parentScrollY);
    }

    const scrollMarginTopValue = scrollMarginTop ?? 0;
    setTimeout(() => {
      const targetLink: HTMLElement | null = document.querySelector(
        `a.${Catalog.constants.activeItemClass}`
      );
      if (contentRef.current && targetLink) {
        contentRef.current.scrollTo({
          top: targetLink.offsetTop - scrollMarginTopValue,
          behavior: 'smooth',
        });

        itemsList.current?.scrollTo({
          top: targetLink.offsetTop - scrollMarginTopValue,
          behavior: 'instant',
        });
      }
    }, 0);

    const sp = new URLSearchParams(searchParams);
    sp.delete('parentScrollY');
    sp.delete('query');
    setSearchParams(sp, { replace: true });

    // We only want to run this on mount, so we disable the exhaustive-deps rule.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [contentRef, isLoading]);

  function onSelect(item: SideCatalogItem, e: React.MouseEvent<HTMLAnchorElement>) {
    userOnSelect?.(item, e);
    if (withRouteTransition) {
      e.preventDefault();
      const anchor = e.currentTarget;
      const href = anchor.getAttribute('href');
      if (!href) return;
      const newURL = new URL(href, window.location.href);
      newURL.searchParams.set('query', queryText);
      newURL.searchParams.set('parentScrollY', String(contentRef.current?.scrollTop ?? 0));
      window.location.href = newURL.toString();
    }
  }

  return { filteredItems, queryText, setQueryText, onSelect };
}

interface SideCatalogProps {
  label: string;
  items: Array<SideCatalogItem>;
  onSelect?: (item: SideCatalogItem, e: React.MouseEvent) => void;
  query?: (s0: string) => Array<SideCatalogItem>;
  isSelected?: (item: SideCatalogItem) => boolean;
  isLoading?: boolean;
  itemPrefix?: string;
  selectedItemLabel?: string;
  withRouteTransition?: boolean;
  scrollMarginTop?: number;
  children?: React.ReactNode;
}

export interface SideCatalogItem {
  title: string;
  url?: string;
  icon?: React.ComponentType<any>;
}
