// packages/ui/src/widgets/VersionSelectDropdown.tsx
import { LuChevronDown } from 'react-icons/lu';

import { ObjectFunctor } from '@repo/utils/std/objects';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '../components/dropdownMenu';

export default function VersionSelectDropdown<
  K extends Record<string, VersionProps>,
>({
  selectedVersion,
  versions,
  onVersionChange,
}: VersionSelectDropdownProps<K>) {
  const versionsObject = new ObjectFunctor(versions)
    .mapValues((key, value) => {
      return {
        displayName: value.displayName || (key as string),
        selected: selectedVersion === key,
        disabled: value.disabled,
      };
    })
    .get();
  return (
    <DropdownMenu>
      <DropdownMenuTrigger className="line-clamp-1 ellipsis">
        {versionsObject[selectedVersion]?.displayName}{' '}
        <LuChevronDown className="inline" />
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        {Object.entries(versionsObject).map(([key, value]) => (
          <DropdownMenuItem
            key={key}
            onClick={() => onVersionChange?.(key)}
            variant={(value.selected && 'selected') || 'default'}
            disabled={value.disabled}
          >
            {value.displayName}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

export interface VersionProps {
  displayName?: string /** Default: version name */;
  disabled?: boolean /** Default: false */;
}
export interface VersionSelectDropdownProps<
  K extends Record<string, VersionProps>,
> {
  selectedVersion: keyof K;
  versions: K;
  onVersionChange?: (version: keyof K) => void;
}

// packages/vue-ui/src/widgets/VersionSelectDropdown.vue
<template>
  <DropdownMenu>
    <DropdownMenuTrigger class="line-clamp-1 ellipsis" :class="focusVisibleRingClass">
      {{ selectedVersionDisplay }}
      <Icon name="i-lucide:chevron-down" class="align-middle" />
    </DropdownMenuTrigger>

    <DropdownMenuContent>
      <DropdownMenuItem
        v-for="(value, key) in processedVersions"
        :key="key"
        :variant="value.selected ? 'selected' : 'default'"
        :disabled="value.disabled"
        class="not-last:mb-1"
        :class="[focusVisibleRingClass, 'focus-visible:bg-primary']"
        @click="emit('versionChange', key)"
      >
        {{ value.displayName }}
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

<script setup lang="ts">
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../components/dropdown-menu'
import { ObjectFunctor } from '@repo/utils/std/objects'
import { computed } from 'vue'

type VersionProps = {
  disabled?: boolean // Default: false
  displayName?: string // Default: version name
}

type VersionSelectDropdownProps = {
  selectedVersion?: string
  versions?: Record<string, VersionProps>
}

const props = withDefaults(defineProps<VersionSelectDropdownProps>(), {
  selectedVersion: '',
  versions: () => ({}),
})

const emit = defineEmits<{
  versionChange: [version: string]
}>()

const focusVisibleRingClass = 'focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-ring'
const processedVersions = computed(() => {
  return new ObjectFunctor(props.versions)
    .mapValues((key, value) => {
      return {
        disabled: value.disabled,
        displayName: value.displayName ?? key,
        selected: props.selectedVersion === key,
      }
    })
    .get()
})

const selectedVersionDisplay = computed(() => {
  const selected = processedVersions.value[props.selectedVersion]
  return selected?.displayName ?? props.selectedVersion
})

export type { VersionSelectDropdownProps, VersionProps }
</script>
